version: '3.1'

services: 
  web:
    image: openjdk:17-alpine
    restart: always
    ports:
      - "80:8080"
    volumes:
      - "./app.jar:/app.jar"
    command: ['java', '-jar', '/app.jar'] 
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      Mongo_INITDB_DATABASE: db_merchant
    ports:
      - 27017:27017
    volumes:
      - ./dbMongo:/data/db
